$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
allowCompoundWords: true
maxNumberOfProblems: 7
dictionaries:
  - en-US
  - bash
  - docker
  - filetypes
  - fullstack
  - golang
  - k8s
  - lorem-ipsum
  - softwareTerms
  - computing-acronyms
ignorePaths:
  - priv/database.bcup
  - bin/cloud-sql-proxy
  - priv/secureBootKeysZ390M
  - bin/baristai
  - bin/dir-rename
  - bin/filer
  - bin/rename
  - bin/typo
  - dotfiles/lib-git-prompt.sh
  - dotfiles/Brewfile
  - etc
  - LICENSE
  - go.mod
  - go.sum
words:
  - abrev
  - ACPI
  - AGDP
  - AHCI
  - aliasg
  - alnum
  - alsa
  - APLF
  - appt
  - APSN
  - AQAAAA
  - argn
  - artis
  - Asam
  - ASPM
  - athenadepartmentid
  - BARC
  - baristai
  - bcup
  - Benzodiazepines
  - blazingly
  - btrfs
  - busid
  - cfprefsd
  - CIWA
  - CIWAB
  - commitlintrc
  - coreutils
  - cpio
  - CPUPM
  - CQAAAA
  - CSSRS
  - csum
  - Cynwyd
  - dator
  - Debugf
  - devmode
  - DMAR
  - DSDT
  - EDID
  - ehff
  - envtest
  - euox
  - fbcon
  - filerrc
  - findutils
  - flansbaum
  - forex
  - Fulgham
  - FUMA
  - FUQQ
  - gcloud
  - gcmsg
  - gcom
  - GIGE
  - GLAN
  - glslang
  - godotenv
  - goqu
  - gosec
  - gotestfmt
  - GPGKEY
  - grbonto
  - grepl
  - grepr
  - groupid
  - gsed
  - guake
  - GULNV
  - HDAS
  - HDEF
  - HECI
  - hipblas
  - hloc
  - HPET
  - IGPU
  - IMEI
  - initdb
  - insuranceid
  - iokit
  - IOUSB
  - IPIC
  - iterm
  - kaue
  - kazuo
  - kdesu
  - kdnssd
  - kexec
  - Kext
  - Kexts
  - Komplete
  - krunner
  - LARRIS
  - ldns
  - ldvalue
  - lemos
  - libavif
  - libheif
  - libmp
  - lzma
  - mackup
  - MCFG
  - meds
  - Mgmt
  - Mikey
  - mkinitcpio
  - mkpath
  - Mooresville
  - mserver
  - msgln
  - MSUD
  - nauck
  - ncdu
  - noatime
  - noconfirm
  - nolint
  - Nower
  - OBAT
  - ollama
  - pacu
  - PAWSS
  - pgdialect
  - pgrep
  - pgsql
  - pids
  - playerctl
  - ppfeaturemask
  - prefs
  - psql
  - QAAA
  - rclone
  - ribeiro
  - rocm
  - SEVDSQ
  - SSDT
  - SSRS
  - stretchr
  - Strs
  - sysu
  - tcodes0
  - teramoto
  - testdb
  - thom
  - thomazella
  - tkdiff
  - tomejila
  - UAAAA
  - ucode
  - uncompress
  - uninteractive
  - unlzma
  - unrar
  - unrequired
  - unxz
  - uptrace
  - USBXHCI
  - USBXHCIPCI
  - USDBRL
  - vacuumdb
  - vite
  - VRTL
  - wneessen
  - Wrapfl
  - XCPM
  - ydeng
  - ZADD
  - ZPJV
  - zram
  - zswap
  - ZYMA
